# Generated by Django 4.2 on 2023-05-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('smil_serial', models.SmallAutoField(primary_key=True, serialize=False)),
                ('smail_integer', models.SmallIntegerField()),
                ('big_integer', models.BigIntegerField()),
                ('numeric', models.FloatField()),
            ],
        ),
    ]
